name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ released, prereleased ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Common Environment
        uses: ./.github/actions/setup-environment

      - name: Run Android Lint (Debug)
        run: ./gradlew lintDebug

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: lint-reports-debug
          path: app/build/reports/lint-results-debug.xml

  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Common Environment
        uses: ./.github/actions/setup-environment

      - name: Run ktlintFormat
        run: ./gradlew :translate-genie:ktlintFormat

      - name: Check for KTLint violations
        run: |
          ./gradlew ktlintCheck
          if [ $? -ne 0 ]; then
            echo "KTLint found violations that could not be automatically fixed."
            exit 1
          fi
  detekt:
    name: Run Detekt Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Common Environment
        uses: ./.github/actions/setup-environment

      - name: Run Detekt and Attempt Auto-Correction
        run: ./gradlew :translate-genie:detekt --auto-correct

      - name: Check for remaining Detekt issues
        run: ./gradlew :translate-genie:detekt

      - name: Upload Detekt reports
        if: failure()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: detekt-reports
          path: |
            **/build/reports/detekt/*.html
            **/build/reports/detekt/*.xml
            **/build/reports/detekt/*.txt
            **/build/reports/detekt/*.sarif
          retention-days: 7
  spotless:
    name: Run Spotless Check
    runs-on: ubuntu-latest
    needs: [ lint, ktlint, detekt ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Common Environment
        uses: ./.github/actions/setup-environment

      - name: Run Spotless Apply
        run: ./gradlew :translate-genie:spotlessApply

      - name: Check for uncommitted Spotless changes
        run: |
          git diff --exit-code --quiet
          if [ $? -ne 0 ]; then
            echo "SpotlessApply has made changes. Please run './gradlew spotlessApply' locally and commit the changes."
            exit 1
          else
            echo "Spotless check passed. No formatting changes needed or changes were already applied."
          fi

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
  build_app:
    name: Build Application
    runs-on: ubuntu-latest
    needs: spotless

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Common Environment
        uses: ./.github/actions/setup-environment

      - name: Build debug APK
        run: ./gradlew assembleDebug
  publish:
    name: publish plugin
    runs-on: macOS-latest
    needs: build_app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Common Environment
        uses: ./.github/actions/setup-environment

      - name: Publish to Gradle Plugins Portal
        run: |
          ./gradlew publishPlugins \
            -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} \
            -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} \
            --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}